version: "3.8"
services:
    
    orbit:
        restart: always
        build:
            context: ./orbit
        ports:
            - "5001:5001"
    qwik-app:
        restart: always
        build:
            context: ./app
        ports:
            - "3030:3030" 
    nginx:
        restart: always
        build:
            context: ./nginx
        ports:
            - "80:80"